name: Run Crawler Test

on:
  workflow_dispatch: # 允許手動點擊按鈕執行

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 supabase

      - name: Run script
        run: python main.py
